version: '3.3'

services:
  frontend:
    image: react-template
    container_name: react-template
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80